create home work 1
OlgaKalininaMTS/AQA_MTS pull request #1
Opened 2023-11-22 16:54 UTC by OlgaKalininaMTS

2023-11-24 22:30 UTC, wildpioneer requested changes

2023-11-24 22:30 UTC, wildpioneer commented on Arrays_hw/Program.cs
> +Console.WriteLine("Введите любое число :");
Не верно созданный Pull Request - не тот target branch выбран

2023-11-24 22:30 UTC, wildpioneer commented on Arrays_hw/Program.cs
> +// Задача 1
А это точно домашняя работа?

2023-11-26 21:56 UTC, wildpioneer requested changes

2023-11-26 21:56 UTC, wildpioneer commented on Arrays_hw/Program.cs
> +foreach (int i in array1)
Пустая строка нужна здесь

2023-11-26 21:56 UTC, wildpioneer commented on Arrays_hw/Program.cs
> +if (b1 == 0)
Пустая строка

2023-11-26 21:56 UTC, wildpioneer commented on Arrays_hw/Program.cs
> +        b1 = 1;
Форматирование

2023-11-26 21:56 UTC, wildpioneer commented on Arrays_hw/Program.cs
> +        b1 = 1;
Для таких целей лучше использовать тип bool

2023-11-26 21:56 UTC, wildpioneer commented on Arrays_hw/Program.cs
> +var rr = new List<int>(array2.GetLength(0));
Мы не знаем коллекций, и решение из-за этого будет сильно отличаться

2023-11-26 21:56 UTC, wildpioneer commented on Arrays_hw/Program.cs
> +foreach (int item in array3)
А с чем связан разные подходы в выводе значений в разных задачах?
var str2 = string.Join(" ", b);
Console.WriteLine(str2);

А тут через foreach?

2023-11-26 21:56 UTC, wildpioneer commented on Arrays_hw/Program.cs
> +Console.WriteLine($"\n Среднее значение массива: {aver}");
Средне-арифметическое и среднее - это два разных числа
"1 5 10" - среднее это 5, а среднеарифметическое 5,3

2023-11-26 21:56 UTC, wildpioneer commented on Arrays_hw/Program.cs
> +Console.WriteLine($"Массив 1:{str14}\nМассив 2:{str24}");
А для чего использовать один Console.WriteLine вместо двух? Это явно усложнило чтение кода

2023-11-26 21:56 UTC, wildpioneer commented on Arrays_hw/Program.cs
> +if (mid < mid2)
нужно использовать else if вместо отдельного полноценного if

2023-11-26 21:56 UTC, wildpioneer commented on Arrays_hw/Program.cs
> +if (mid == mid2)
нужно использовать else if вместо отдельного полноценного if

2023-11-27 16:20 UTC, OlgaKalininaMTS commented on Arrays_hw/Program.cs
> +foreach (int item in array3)
Сначала думаю как решить задачу с точки зрения математики, потом начинаю думаю (решаю) как могу это реализовать с помощью c# (либо с помощью того, что проходили на лекции, либо читаю дополнительную информацию в интернете)

2024-01-29 10:09 UTC, closed without merging

2024-01-29 10:09 UTC, wildpioneer commented
Проверено