Delegate hw
OlgaKalininaMTS/AQA_MTS pull request #6
Opened 2024-02-10 16:53 UTC by OlgaKalininaMTS

Домашняя работа по Delegate

2024-03-19 14:33 UTC, wildpioneer requested changes

2024-03-19 14:33 UTC, wildpioneer commented on Delegate/Exercise1.cs
> +        Random rnd = new Random();
А ты не используешь делегат - ты просто взяла рандомное число из класса Random.

2024-03-19 14:33 UTC, wildpioneer commented on Delegate/Exercise2.cs
> +public delegate double Exercise2(double radius);  // �������, ������� ��������� �� �����
И этот делегат нигде не используется

2024-03-23 13:41 UTC, OlgaKalininaMTS commented on Delegate/Exercise1.cs
> +        Random rnd = new Random();
Замечания исправлены

2024-03-23 13:43 UTC, OlgaKalininaMTS commented on Delegate/Exercise2.cs
> +public delegate double Exercise2(double radius);  // �������, ������� ��������� �� �����
Замечания исправлены

2024-04-09 09:22 UTC, wildpioneer commented
Проверено

2024-04-09 09:22 UTC, closed without merging